function main()
    clear
    close all
    clc
    % Число частиц
    N = 6;
    % Создаем GUI
    fid1 = figure;
    set(fid1,'position',[200 200 700 600])
    ax1 = axes('Units','normalized','position',[0.3 0.1 0.65, 0.8]);
    hold on;
    vs_text = uicontrol(fid1,...
        'Style', 'text',...
        'Units','normalized',...
        'Position',[0.4 0.9 0.4, 0.05],...
        'String','');
    q_text = uicontrol(fid1,...
        'Style', 'text',...
        'Units','normalized',...
        'Position',[0.07 0.8 0.1, 0.05],...
        'String','Кратность:');
    q_edit = uicontrol(fid1,...
        'Style', 'edit',...
        'Units','normalized',...
        'Position',[0.07 0.77 0.1, 0.05],...
        'String','10');
    e_text = uicontrol(fid1,...
        'Style', 'text',...
        'Units','normalized',...
        'Position',[0.07 0.7 0.1, 0.05],...
        'String','Заряд:');
    e_edit = uicontrol(fid1,...
        'Style', 'edit',...
        'Units','normalized',...
        'Position',[0.07 0.67 0.1, 0.05],...
        'String','1.6e-19');
    V_text = uicontrol(fid1,...
        'Style', 'text',...
        'Units','normalized',...
        'Position',[0.07 0.58 0.1, 0.07],...
        'String','Внешнее поле:');
    V_edit = uicontrol(fid1,...
        'Style', 'edit',...
        'Units','normalized',...
        'Position',[0.07 0.55 0.1, 0.05],...
        'String','1000');
    R_text = uicontrol(fid1,...
        'Style', 'text',...
        'Units','normalized',...
        'Position',[0.07 0.43 0.1, 0.1],...
        'String','Радиус равновесной орбиты:');
    R_edit = uicontrol(fid1,...
        'Style', 'edit',...
        'Units','normalized',...
        'Position',[0.07 0.37 0.1, 0.05],...
        'String','10');
    
    global q e U Rs
    
    % Пока не закрыли окно
    while ishandle(fid1)
       
        % Кратность ускорения
        q = str2double(get(q_edit,'String'));
        % Заряд
        e = str2double(get(e_edit,'String'));
        % Ускоряющее напряжение
        U = str2double(get(V_edit,'String'));
        % Радиус ускорителя, м
        Rs = str2double(get(R_edit,'String'));
        for i = 1:N
            % Рассчитываем N частиц
            [t,R,ang,vs] = synchrophasotron();
            RR(i,:) = R;
            ANG(i,:) = ang;
            figure(fid1)
            plt1(i) = plot(0,0);
            plt2(i) = plot(0,0,'o');
        end;

        axis equal
        xlim(gca,[-1.3*Rs,1.3*Rs]);
        ylim(gca,[-1.3*Rs,1.3*Rs]);
        grid on
        plt3 = plot(Rs*cos(-pi:pi/100:pi),Rs*sin(-pi:pi/100:pi),'k--');

        X = RR(:,:).*cos(ANG(:,:));
        Y = RR(:,:).*sin(ANG(:,:));
        color=[[1 0 0];[0 1 0];[0 0 1];[0.5 0.5 0.5];[0.2 0.7 0.5];[0.7 0.3 0.4]];
        for j=11:length(t)
            for i=1:N 
            set(plt1(i),...
              'XData',X(i,j-10:j),...
              'Ydata',Y(i,j-10:j),...
              'Color', color(i,:));
            set(plt2(i),...
              'XData',X(i,j),...
              'Ydata',Y(i,j),...
              'MarkerFaceColor', color(i,:));
            end
            
            set(vs_text,'String',sprintf('Текущая равновесная скорость v_s=%1.3f', vs(j)));
            drawnow();
            pause(0.005)
        end
    end
end
