function menu
   %  Create and then hide the GUI as it is being constructed.
   f = figure('Visible','off','Position',[360,500,600,400]);
 
   % Construct the components   
   uicontrol('Style','text',...
        'String', 'Очередь',...
        'ForegroundColor',[1 0 0],...
        'FontSize',20,...
        'FontWeight','bold',...
        'HorizontalAlignment','center',...
        'Units','normalized',...
        'Position',[.1 .9 .8 .08]);
   
   hpanel = uipanel('Position',[.03 .3 .4 .55],'Title','Parameters:');
   hpanel2 = uipanel('Position',[.53 .3 .4 .55],...
       'BackgroundColor','white');
   hresult_text = uicontrol('Parent', hpanel2,...
        'Style','text',...
        'String', 'Здесь будут отображаться данные об автомобилях, полученных из очереди',...
        'ForegroundColor',[0.5 0.5 0.5],...
        'HorizontalAlignment','left',...
        'Units','normalized',...
        'Position',[.05 .05 .9 .9],...
        'BackgroundColor','white');

   hcount = uicontrol('Style','text',...
       'String',strcat('Элементов в очереди: 0'),...
       'Units','normalized',...
       'HorizontalAlignment','right',...
       'Position',[.53 .05 .4 .05]);
 
    hid_text = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'ID:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .85 .2 .08]);
    hid = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .85 .6 .08]);
    
    hmake_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Make:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .75 .2 .08]);
    hmake  = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .75 .6 .08]);
    
    hmodel_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Model:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .65 .2 .08]);
    hmodel = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .65 .6 .08]);
    
    hyear_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Year:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .55 .2 .08]);
    hyear = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .55 .6 .08]);
    
    htransmission_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Transm.:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .45 .2 .08]);
    htransmission = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .45 .6 .08]);
    
    hengine_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Engine:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .35 .2 .08]);
    hengine = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .35 .6 .08]);
    
    hdrive_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Drive:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .25 .2 .08]);
    hdrive = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .25 .6 .08]);
    
    hcolor_text  = uicontrol('Parent', hpanel,...
        'Style','text',...
        'String', 'Color:',...
        'HorizontalAlignment','right',...
        'Units','normalized',...
        'Position',[.05 .15 .2 .08]);
    hcolor = uicontrol('Parent', hpanel,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[.3 .15 .6 .08]);
    hadd_button = uicontrol('Style','pushbutton',...
        'String','Добавить автомобиль в очередь',...
        'Units','normalized',...
        'Position',[.03 .18 .3 .1],...
        'Callback',@add_button_callback);
    hget_button = uicontrol('Style','pushbutton',...
        'String','Извлечь автомобиль из очереди',...
        'Units','normalized',...
        'Position',[.03 .05 .3 .1],...
        'Callback',@get_button_callback);

   q = FIFOQueue;
   
   % Assign the GUI a name to appear in the window title.
   f.Name = 'Работа с очередью';
   
   % Move the GUI to the center of the screen.
   movegui(f,'center')
   
   % Make the GUI visible.
   f.Visible = 'on';
 
   %  Callbacks
   function add_button_callback(source,eventdata)
       hresult_text.ForegroundColor = [0 0 0];
       if isempty(hid.String)
           hresult_text.ForegroundColor = [1 0 0];
           hresult_text.String = 'Поле ID обязательное для ввода';
           return
       end
       car = Car(str2double(hid.String));
       car.addfield('make',hmake.String,...
             'model',hmodel.String,...
             'year',str2double(hyear.String),...
             'transmission',htransmission.String,...
             'engine',hengine.String,...
             'drive_type',hdrive.String,...
             'color',hcolor.String);
       addtail(q,car)
       hid.String = '';
       hmake.String = '';
       hmodel.String = '';
       hyear.String = '';
       htransmission.String = '';
       hengine.String = '';
       hdrive.String = '';
       hcolor.String = '';
       
       hresult_text.String = 'Данные добавлены в очередь';
       hcount.String = strcat('Элементов в очереди:   ',num2str(q.get_count));
   end

   function get_button_callback(source,eventdata)
       count = q.get_count;
       hresult_text.ForegroundColor = [0 0 0];
       if count==0
           hresult_text.ForegroundColor = [1 0 0];
           hresult_text.String = 'В очереди нет элементов';
           return
       end
       car = q.dequeue;
       result_text = sprintf('ID: %d\nMake: %s\nModel: %s\nYear: %d\nTransm.: %s\nEngine: %s\nDrive: %s\nColor: %s\n',...
           car.id,car.make,car.model,car.year,car.transmission,car.engine,car.drive_type,car.color);
       hresult_text.String = result_text;
       hcount.String = strcat('Элементов в очереди:   ',num2str(q.get_count));      
   end
  
   
end 