clear all
clc
% Тест на скорость. Если выполняется долго, можно увеличить REFLENGTH в
% FIFOQueue.m, однако данные будут занимать больше места
tic
qu=FIFOQueue;
for i=1:10000
    qu.enqueue(Car(i))
end

while ~q.isempty
    c=q.dequeue;
end
toc

% Тест на заполнение очереди объектами класса Car

% Создаем очередь
q=FIFOQueue;

% Создаем автомобиль
car=Car(1);
% Добавляем параметры автомобиля
car.addfield('make','bmw',...
             'model','m3',...
             'year',2016,...
             'transmission','8AT',...
             'engine','5.0',...
             'drive_type','RWD',...
             'color','red');
% Добавляем автомобиль в очередь
q.enqueue(car);

% Аналогично создаем другие автомобили и добавляем их в очередь
car=Car(2);
car.addfield('make','ВАЗ',...
             'model','2107',...
             'year',1995,...
             'transmission','4MT',...
             'engine','1.4',...
             'drive_type','RWD',...
             'color','white');
q.enqueue(car);

car=Car(3);
car.addfield('make','Nissan',...
             'model','Juke',...
             'year',2011,...
             'transmission','CVT',...
             'engine','1.6T',...
             'drive_type','AWD',...
             'color','black');
q.enqueue(car);

car=Car(4);
car.addfield('make','Tesla',...
             'model','ModelS',...
             'year',2015,...
             'transmission',[],...
             'engine','Electro',...
             'drive_type','AWD',...
             'color','red');
q.enqueue(car);

car=Car(5);
car.addfield('make','Hyundai',...
             'model','Creta',...
             'year',2016,...
             'transmission','6AT',...
             'engine','1.6 CRDi VGT',...
             'drive_type','AWD',...
             'color','black');
q.enqueue(car);

car=Car(6);
car.addfield('make','Ford',...
             'model','Model T',...
             'year',1908,...
             'transmission','2PG',...
             'engine','2.9',...
             'drive_type','RWD',...
             'color','black');
q.enqueue(car);

car=Car(7);
car.addfield('make','ВАЗ',...
             'model','Priora',...
             'year',2010,...
             'transmission','5MT',...
             'engine','2.9',...
             'drive_type','FWD',...
             'color','white');
q.enqueue(car);
